config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :tasks

  # Add a new route for the 'my_tasks' page
  get '/my_tasks', to: 'tasks#my_tasks', as: 'my_tasks'
  get '/all_tasks', to: 'tasks#all_tasks', as: 'all_tasks'

  
  root 'tasks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
    validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
#This is the top level post controller coment
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]


  protect_from_forgery with: :exception, unless: -> {request.format.json?}

  include TasksHelper  # Include the helper module



  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /my_tasks
  def my_tasks
    @tasks = Task.all
  end

  # GET /all_tasks
  def all_tasks
    @tasks = Task.all
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to task_url(@task), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to task_url(@task), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy!

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title, :description, :due_date, :priority, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def render_tasks(tasks)
    tasks.each do |task|
      render partial: 'task', locals: { task: task }
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to 'Task Management System', root_path, class: 'navbar-brand' %>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to 'My Tasks', my_tasks_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'All Tasks', all_tasks_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'New Task', new_task_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="container mt-4">
  <%= yield %>
</div>
   
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= post.body %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :due_date, style: "display: block" %>
    <%= form.datetime_field :due_date %>
  </div>

  <div>
    <%= form.label :priority, style: "display: block" %>
    <%= form.number_field :priority %>
  </div>

  <div>
    <%= form.label :completed, style: "display: block" %>
    <%= form.check_box :completed %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
  <p>
    <strong>Title:</strong>
    <%= task.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= task.description %>
  </p>

  <p>
    <strong>Due date:</strong>
    <%= task.due_date %>
  </p>

  <p>
    <strong>Priority:</strong>
    <%= task.priority %>
  </p>

  <p>
    <strong>Completed:</strong>
    <%= task.completed %>
  </p>

</div>

app/views/tasks/all_tasks.html.erb
<p style="color: green"><%= notice %></p>


<h1>All Tasks</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Due Date</th>
      <th>Priority</th>
      <th>Completed</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.due_date %></td>
        <td><%= task.priority %></td>
        <td><%= task.completed %></td>
        <td>
          <%= link_to 'Show', task %> 
          <%= link_to 'Edit', edit_task_path(task) %>
          <%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tasks/edit.html.erb
<p style="color: green"><%= notice %></p>
<h1>Editing task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Show this task", @task %> |
  <%= link_to "Edit", edit_task_path(@task) %> 
  <%= link_to "Back to tasks", tasks_path %>
</div>

app/views/tasks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Manage Tasks</h1> 

<div class="text-center mt-4">
<%= link_to 'New task', new_task_path, class: 'btn btn-primary btn-lg' %>
</div>



<div class="row">
  <div class="col-md-4">
    <h2>My Tasks</h2>
    <% @tasks.each do |task| %>
      <div class="card mb-3">
        <div class="card-body">
          <h5 class="card-title"><%= task.title %></h5>
          <p class="card-text"><strong>Status:</strong> <%= task.completed %></p>
          <%= link_to 'Show', task, class: 'btn btn-primary btn-sm' %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="col-md-4">
    <h2>In Progress</h2>
    <% @tasks.each do |task| %>
      <div class="card mb-3">
        <div class="card-body">
          <h5 class="card-title"><%= task.title %></h5>
          <p class="card-text"><strong>Status:</strong> <%= task.completed %></p>
          <%= link_to 'Show', task, class: 'btn btn-primary btn-sm' %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="col-md-4">
    <h2>Completed</h2>
    <% @tasks.each do |task| %>
      <div class="card mb-3">
        <div class="card-body">
          <h5 class="card-title"><%= task.title %></h5>
          <p class="card-text"><strong>Status:</strong> <%= task.completed %></p>
          <%= link_to 'Show', task, class: 'btn btn-primary btn-sm' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks/my_tasks.html.erb
<!-- app/views/tasks/my_tasks.html.erb -->

<h1>Tasks</h1>

<div class="row">
  <div class="col-md-12">
    <% @tasks.each do |task| %>
      <div class="card mb-3">
        <div class="card-body">
          <h5 class="card-title"><%= task.title %></h5>
          <p class="card-text"><strong>Status:</strong> <%= task.completed %></p>
          <%= link_to 'Show', task, class: 'btn btn-primary btn-sm' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Back to tasks", tasks_path %>
</div>

app/views/tasks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @task %>

<div>
  <%= link_to "Edit", edit_task_path(@task) %> |
  
  <%= link_to "Back", tasks_path %>  

  <%= button_to "Destroy this task", @task, method: :delete %>
</div>